"""empty message

Revision ID: 55cf1894b351
Revises: 211cfb354d05
Create Date: 2026-03-22 16:17:23.820672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cf1894b351'
down_revision = '211cfb354d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('character_planet_of_origin_fkey'), type_='foreignkey')
        batch_op.drop_column('planet_of_origin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_of_origin', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('character_planet_of_origin_fkey'), 'planet', ['planet_of_origin'], ['id'])

    # ### end Alembic commands ###
