"""empty message

Revision ID: c01c9e52a1c6
Revises: be91c4e7c265
Create Date: 2026-03-23 19:19:12.613566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01c9e52a1c6'
down_revision = 'be91c4e7c265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_of_origin_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('character_planet_of_origin_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_of_origin_id'], ['id'])
        batch_op.drop_column('planet_of_origin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_of_origin', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('character_planet_of_origin_fkey'), 'planet', ['planet_of_origin'], ['id'])
        batch_op.drop_column('planet_of_origin_id')

    # ### end Alembic commands ###
